### ISSUE TITLE
Panic will occur when accepting 

### ISSUE THREAD

**Issue by SheepYangXin** [tidwall/evio#51]
panic: no such file or directory

goroutine 50 [running]:
github.com/tidwall/evio/internal.(*Poll).ModReadWrite(0xc4202ea060, 0x507)
	/xagiot/home/yangxin/iot-proxy/src/github.com/tidwall/evio/internal/internal_linux.go:116 +0x8c
github.com/tidwall/evio.loopRead(0xc42030a000, 0xc4202d0100, 0xc4209c9050, 0xc4208ffb70, 0x0)
	/xagiot/home/yangxin/iot-proxy/src/github.com/tidwall/evio/evio_unix.go:445 +0x17d
github.com/tidwall/evio.loopRun.func2(0x507, 0x0, 0x0, 0x0, 0x0)
	/xagiot/home/yangxin/iot-proxy/src/github.com/tidwall/evio/evio_unix.go:245 +0xe6
github.com/tidwall/evio/internal.(*Poll).Wait(0xc4202ea060, 0xc420a93fa8, 0xc42030a000, 0x0)
	/xagiot/home/yangxin/iot-proxy/src/github.com/tidwall/evio/internal/internal_linux.go:66 +0xb3
github.com/tidwall/evio.loopRun(0xc42030a000, 0xc4202d0100)
	/xagiot/home/yangxin/iot-proxy/src/github.com/tidwall/evio/evio_unix.go:230 +0x93
created by github.com/tidwall/evio.serve
	/xagiot/home/yangxin/iot-proxy/src/github.com/tidwall/evio/evio_unix.go:157 +0x483

I thought there have some exception in listen unsolve, so sometimes evio will panic without any recover.
I‘m looking forward to hearing from you, best wishs to U.

**Comment by tidwall** [comment]
Thanks for reporting. I would like to reproduce this issue on my side. Could you provide some information on your platform, Go version, and, if possible, code that causes this panic?
